# Generated by Django 4.1.5 on 2023-02-13 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=20)),
                ('item_name', models.CharField(max_length=255)),
                ('item_description', models.TextField()),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item_qty', models.PositiveIntegerField()),
                ('item_picture', models.ImageField(upload_to='items/')),
            ],
        ),
    ]
