# Generated by Django 4.1.5 on 2023-02-20 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Nid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nid_number', models.IntegerField(max_length=20)),
                ('issue_date', models.DateField()),
                ('expire_date', models.DateField()),
                ('citizen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nid', to='nid.citizen')),
            ],
        ),
    ]
